#!/usr/bin/env bash
# =============================================================================
#  Parametric study launcher — Grid Factor sweep, selectable turbulence model
#
#  Usage:
#    ./run_study.sh wilcox        # Wilcox journal
#    ./run_study.sh omegasst      # OmegaSST journal
#    ./run_study.sh               # no argument → interactive menu
#
#  For each grid factor entry:
#    1. Patch grid_factor in parameter.yml
#    2. Generate base geometry  →  BASE_DIR/{sim_name}/
#    3. Run gmcPlay with the journal of the selected model
#    4. Write sim_config.yml
#    5. Upload to HPC
#    6. Submit sbatch job
#    7. Delete from testGEO
# =============================================================================

# ── Environment ───────────────────────────────────────────────────────────────
module load trace_dependencies/gcc-11.4.0-trace-9.7.5-1
module load gmc/9.6.13
module load pymesh/2.0.1-numpy
module load tecplot
module load trace_suite/9.8.0-double

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR="/your/path/testGEO"
HPC_SCRATCH="/your/path/hpc/sims"
HPC_HOST="your.hpc.host"
SBATCH_SCRIPT="/your/path/tracestart_OG.sh"
TRACE_INPUT_SRC_0="/your/path/mod_files/X_offset_0/CORR_PRESSURE/TRACE_entry.input"
INPUT_JOU_0="/your/path/mod_files/X_offset_0/CORR_PRESSURE/TRACE_input.jou"

PARAM_YML="/your/path/testcase/examples/cavity/parameter.yml"
GEO_YML="/your/path/testcase/examples/cavity/geometry.yml"

MODELS_DIR="/your/path/models"

# ── Model selection ───────────────────────────────────────────────────────────
# Each model defines: journal file, label written to sim_config.yml,
# and a prefix put in front of the sim names (e.g. wAA4 vs wLOAA4).
select_model() {
    case "$1" in
        wilcox)
            MODEL_JOU="${MODELS_DIR}/Wilcox1988_KatoLaunder_StreamlineCurvature.jou"
            MODEL_LABEL="Wilcox"
            SIM_PREFIX="w"
            ;;
        omegasst)
            MODEL_JOU="${MODELS_DIR}/OmegaSST_Off_Bardina.jou"
            MODEL_LABEL="OmegaSST"
            SIM_PREFIX="wLO"
            ;;
        *)
            return 1
            ;;
    esac
}

MODEL_CHOICE="${1:-}"

if [ -z "${MODEL_CHOICE}" ]; then
    echo "Select turbulence model:"
    select MODEL_CHOICE in wilcox omegasst; do
        [ -n "${MODEL_CHOICE}" ] && break
    done
fi

if ! select_model "${MODEL_CHOICE}"; then
    echo "ERROR: unknown model '${MODEL_CHOICE}'. Use: wilcox | omegasst"
    exit 1
fi

if [ ! -f "${MODEL_JOU}" ]; then
    echo "ERROR: journal not found: ${MODEL_JOU}"
    exit 1
fi

echo "Model:   ${MODEL_LABEL}"
echo "Journal: ${MODEL_JOU}"
echo "Prefix:  ${SIM_PREFIX}"
echo ""

# ── Hardcoded grid factor list: "BASE_NAME GF_VALUE" ─────────────────────────
# Final sim name = SIM_PREFIX + BASE_NAME  (e.g. w + AA4 → wAA4)
declare -a GF_ENTRIES=(
     "AA4 0.265"
     "AA3 0.405"
     "AA2 0.62"
     "AA1 1.0"
     "AB5 0.22"
     "AB4 0.337"
     "AB3 0.515"
     "AB2 0.826"
     "AB1 1.214"
     "BA4 0.186"
     "BA3 0.315"
     "BA2 0.552"
     "BA1 1.0"
     "BB5 0.155"
     "BB4 0.265"
     "BB3 0.46"
     "BB2 0.826"
     "BB1 1.37"
     "CA4 0.134"
     "CA3 0.253"
     "CA2 0.493"
     "CA1 1.0"
     "CB4 0.114"
     "CB3 0.21"
     "CB2 0.405"
     "CB1 0.826"
)

# ── Helper: patch grid_factor in parameter.yml ────────────────────────────────
patch_grid_factor() {
    local yml="$1"
    local gf="$2"
    sed -i "s/^\(\s*grid_factor:\s*\)[0-9.e+-]*/\1${gf}/" "$yml"
}

# ── Helper: write sim_config.yml ──────────────────────────────────────────────
write_sim_config() {
    local dir="$1"
    local sim_name="$2"
    local gf="$3"

    cat > "${dir}/sim_config.yml" <<EOF
# sim_config.yml — auto-generated by run_study.sh
# ----------------------------------------------------
sim_name:           ${sim_name}
grid_factor:        ${gf}
turbulence_model:   ${MODEL_LABEL}
EOF
}

# =============================================================================
#  MAIN LOOP
# =============================================================================
total_submitted=0

for entry in "${GF_ENTRIES[@]}"; do
    read -r base_name gf_val <<< "$entry"
    sim_name="${SIM_PREFIX}${base_name}"

    base_dir="${BASE_DIR}/${sim_name}"

    echo "======================================================================"
    echo "  Grid factor: ${sim_name}  (GF = ${gf_val})  [${MODEL_LABEL}]"
    echo "======================================================================"

    # ── 1. Patch grid_factor into parameter.yml ────────────────────────────
    echo "  Patching grid_factor = ${gf_val} in ${PARAM_YML}"
    patch_grid_factor "${PARAM_YML}" "${gf_val}"

    # ── 2. Generate base geometry ──────────────────────────────────────────
    echo "  Generating base geometry → ${base_dir}"

    cd /your/path/testcase/lab_altered_py

    module load pymesh/2.0.1-numpy
    PyMesh.x main.py \
        -p "${PARAM_YML}" \
        -g "${GEO_YML}" \
        -c "${base_dir}"
    module unload pymesh/2.0.1-numpy
    module load trace_suite/9.8.0-double

    cd "${base_dir}/input"

    #ENTRYINPUT
    #cp "${TRACE_INPUT_SRC_0}" "${BASE_DIR}/${sim_name}/input/TRACE_entry.input"
    #gmcPlay "${INPUT_JOU_0}"

    prep.py -clb -cgns TRACE.cgns -np 128 -sb TRACE_split.cgns splitScript.jou mergeScript.jou
    gmcPlay splitScript.jou

    cp "${PARAM_YML}" "${base_dir}/parameters_used.yml"
    cp "${GEO_YML}"   "${base_dir}/geometry_used.yml"

    # ── Patch TRACE_control.input ──────────────────────────────────────────
    # WriteCellResidual lines intentionally commented out — do not re-enable
    # without checking residual output behaviour first.
    # CONTROL_FILE="${base_dir}/input/TRACE_control.input"
    # printf '\nAll immediate\nWriteCellResidual\n' >> "${CONTROL_FILE}"

    # ── 3. Apply the selected model journal ─────────────────────────────────
    gmcPlay "${MODEL_JOU}"

    # ── 4. Write sim_config.yml ──────────────────────────────────────────────
    write_sim_config "${base_dir}" "${sim_name}" "${gf_val}"

    # ── 5. Upload to HPC ──────────────────────────────────────────────────────
    echo "  Uploading ${sim_name} → ${HPC_HOST}:${HPC_SCRATCH}"
    scp -r "${base_dir}" "${HPC_HOST}:${HPC_SCRATCH}"

    # ── 6. Submit sbatch job ─────────────────────────────────────────────────
    ssh "${HPC_HOST}" \
        "sbatch --chdir=${HPC_SCRATCH}/${sim_name}/input ${SBATCH_SCRIPT}"

    # ── 7. Delete from testGEO ───────────────────────────────────────────────
    echo "  Cleaning up: ${base_dir}"
    rm -rf "${base_dir}"

    total_submitted=$(( total_submitted + 1 ))
    echo "  Submitted & cleaned: ${sim_name}"
    echo ""

done

echo "======================================================================"
echo "  All done. Total simulations submitted: ${total_submitted}"
echo "======================================================================"
