#!/usr/bin/env bash
# =============================================================================
#  Parametric study launcher — Fin Count x Step Profile sweep, single Wilcox journal
#
#  Hardcoded step-height profiles (label + constant step height value):
#    FS   =  0.000   (smooth)
#    FC   = -0.002   (convergent)
#    FD   =  0.002   (divergent)
#    FCH  = -0.001   (convergent, half)
#    FDH  =  0.001   (divergent, half)
#
#  For each profile, sweeps number_of_fins from 1 to 9. For each fin count N:
#    - number_of_fins  = N
#    - number_of_steps = N - 1   (step_height array has N-1 entries)
#    - every entry in step_height is set to the profile's constant value
#
#  Total runs: 5 profiles x 9 fin counts = 45 simulations, one script invocation.
#
#  sim_name = <PROFILE_LABEL>_F<N>   e.g. FC_F4, FDH_F7, FS_F1 ...
#
#  For each (profile, fin count) entry:
#    1. Patch number_of_fins + step_height in geometry.yml
#    2. Generate base geometry  →  BASE_DIR/{sim_name}/
#    3. Prep geometry (split/merge)
#    4. Apply model journal via gmcPlay
#    5. Write sim_config.yml
#    6. Upload to HPC
#    7. Submit sbatch job
# =============================================================================

# ── Environment ───────────────────────────────────────────────────────────────
module load trace_dependencies/gcc-11.4.0-trace-9.7.5-1
module load gmc/9.6.13
module load pymesh/2.0.1-numpy
module load tecplot
module load trace_suite/9.8.0-double

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR="/home/corr_mi/Projects/MM/testGEO"
HPC_SCRATCH="/scratch/ws25/corr_mi-den_mig/sims"
HPC_HOST="cara.dlr.de"
SBATCH_SCRIPT="/scratch/ws25/corr_mi-RestoredMig/corr_mi-workmig-1779156012/tracestart_OG.sh"
TRACE_INPUT_SRC_0="/localdata1/corr_mi/mod_files/X_offset_0/CORR_PRESSURE/TRACE_entry.input"
INPUT_JOU_0="/localdata1/corr_mi/mod_files/X_offset_0/CORR_PRESSURE/TRACE_input.jou"
PARAM_YML="/localdata1/testcases/staggered-labyrinth-seal_new/examples/Denecke_cavity/parameter.yml"
GEO_YML="/localdata1/testcases/staggered-labyrinth-seal_new/examples/Denecke_cavity/geometry.yml"

# ── Hardcoded step-height profiles: "LABEL STEP_HEIGHT_VALUE" ────────────────
declare -a STEP_PROFILES=(
    "sFS   0.000"    # smooth
    "sFC  -0.002"    # convergent
    "sFD   0.002"    # divergent
    "sFCH -0.001"    # convergent, half
    "sFDH  0.001"    # divergent, half
)

# ── Fin count range: 1 to 9 fins (9 simulations per profile) ─────────────────
FIN_COUNTS=(1 2 3 4 5 6 7 8 9)

# ── Helper: build a step_height array literal with N entries, all = value ────
# N = 0  → "[]"   (1 fin → 0 steps)
build_step_height_array() {
    local count="$1"
    local val="$2"

    if (( count <= 0 )); then
        echo "[]"
        return
    fi

    local arr=()
    local i
    for (( i = 0; i < count; i++ )); do
        arr+=("${val}")
    done

    local joined
    joined=$(IFS=,; echo "${arr[*]}")
    echo "[${joined}]"
}

# ── Helper: patch number_of_fins + step_height in geometry.yml ───────────────
patch_geometry() {
    local yml="$1"
    local nfins="$2"
    local step_arr="$3"

    # number_of_fins: <int>
    sed -i "s/^\(\s*number_of_fins:\s*\)[0-9]*/\1${nfins}/" "${yml}"

    # step_height: [ ... ]   (replace whatever array is currently there)
    sed -i "s|^\(\s*step_height:\s*\)\[[^]]*\]|\1${step_arr}|" "${yml}"
}

# ── Helper: write sim_config.yml ──────────────────────────────────────────────
write_sim_config() {
    local dir="$1"
    local sim_name="$2"
    local nfins="$3"
    local nsteps="$4"
    local step_val="$5"

    cat > "${dir}/sim_config.yml" <<EOF
# sim_config.yml — auto-generated by run_study.sh
# ----------------------------------------------------
sim_name:           ${sim_name}
number_of_fins:     ${nfins}
number_of_steps:    ${nsteps}
step_height_value:  ${step_val}
turbulence_model:   Wilcox
EOF
}

# =============================================================================
#  MAIN LOOP  —  5 profiles x 9 fin counts = 45 simulations
# =============================================================================
total_submitted=0

for profile in "${STEP_PROFILES[@]}"; do
    read -r profile_label step_val <<< "${profile}"

for n_fins in "${FIN_COUNTS[@]}"; do

    sim_name="${profile_label}_F${n_fins}"
    n_steps=$(( n_fins - 1 ))
    step_arr=$(build_step_height_array "${n_steps}" "${step_val}")

    base_dir="${BASE_DIR}/${sim_name}"

    echo "======================================================================"
    echo "  Sim: ${sim_name}   profile=${profile_label}  fins=${n_fins}  steps=${n_steps}  step_height=${step_val}"
    echo "======================================================================"

    # ── 1. Patch geometry.yml ───────────────────────────────────────────────
    echo "  Patching number_of_fins=${n_fins}, step_height=${step_arr} in ${GEO_YML}"
    patch_geometry "${GEO_YML}" "${n_fins}" "${step_arr}"

    # ── 2. Generate base geometry ──────────────────────────────────────────
    echo "  Generating base geometry → ${base_dir}"

    cd /localdata1/testcases/staggered-labyrinth-seal_new/lab_altered_py

    module load pymesh/2.0.1-numpy
    PyMesh.x main.py \
        -p "${PARAM_YML}" \
        -g "${GEO_YML}" \
        -c "${base_dir}"
    module unload pymesh/2.0.1-numpy
    module load trace_suite/9.8.0-double

    cd "${base_dir}/input"

    #ENTRYINPUT
    cp "${TRACE_INPUT_SRC_0}" "${BASE_DIR}/${sim_name}/input/TRACE_entry.input"
    gmcPlay "${INPUT_JOU_0}"

    # ── 3. Prep geometry (split/merge) ─────────────────────────────────────
    prep.py -clb -cgns TRACE.cgns -np 128 -sb TRACE_split.cgns splitScript.jou mergeScript.jou
    gmcPlay splitScript.jou

    cp "${PARAM_YML}" "${base_dir}/parameters_used.yml"
    cp "${GEO_YML}"   "${base_dir}/geometry_used.yml"

    # ── 4. Apply the model journal ──────────────────────────────────────────
    gmcPlay /home/corr_mi/Projects/MM/models/OmegaSST_Off_Bardina.jou

    # ── 5. Write sim_config.yml ──────────────────────────────────────────────
    write_sim_config "${base_dir}" "${sim_name}" "${n_fins}" "${n_steps}" "${step_val}"

    # ── 6. Upload to HPC ──────────────────────────────────────────────────────
    echo "  Uploading ${sim_name} → ${HPC_HOST}:${HPC_SCRATCH}"
    scp -r "${base_dir}" "${HPC_HOST}:${HPC_SCRATCH}"

    # ── 7. Submit sbatch job ─────────────────────────────────────────────────
    ssh "${HPC_HOST}" \
        "sbatch --chdir=${HPC_SCRATCH}/${sim_name}/input ${SBATCH_SCRIPT}"

    total_submitted=$(( total_submitted + 1 ))
    echo "  Submitted: ${sim_name}"
    echo ""

done   # fin count loop
done   # profile loop

echo "======================================================================"
echo "  All done. Total simulations submitted: ${total_submitted}"
echo "======================================================================"
