#!/usr/bin/env bash
# =============================================================================
#  Parametric study launcher — Grid Factor × SST model combos
#
#  For each grid factor entry:
#    1. Patch grid_factor in parameter.yml
#    2. Generate base geometry  →  BASE_DIR/{sim_name}/
#       (kept in testGEO, NOT uploaded)
#    3. For each of the 2 SST combos:
#       a. Copy base dir  →  BASE_DIR/{sim_name}_{stag}_{rot}/
#       b. Apply SST journal
#       c. Write sim_config.yml
#       d. Upload variant to HPC
#       e. Submit sbatch job
#       f. Delete variant from testGEO (keep base)
# =============================================================================

# ── Environment ───────────────────────────────────────────────────────────────
module load trace_dependencies/gcc-11.4.0-trace-9.7.5-1
module load gmc/9.6.13
module load pymesh/2.0.1-numpy
module load tecplot
module load trace_suite/9.8.0-double

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR="/home/corr_mi/Projects/MM/testGEO"
JOU_DIR="/home/corr_mi/Projects/MM/models"
HPC_SCRATCH="/scratch/ws25/corr_mi-den_mig/sims"
HPC_HOST="cara.dlr.de"
SBATCH_SCRIPT="/scratch/ws25/corr_mi-RestoredMig/corr_mi-workmig-1779156012/tracestart_OG.sh"

PARAM_YML="/localdata1/testcases/staggered-labyrinth-seal_new/examples/Denecke_cavity/parameter.yml"
GEO_YML="/localdata1/testcases/staggered-labyrinth-seal_new/examples/Denecke_cavity/geometry.yml"

# ── Hardcoded grid factor list: "SIM_NAME GF_VALUE" ──────────────────────────
declare -a GF_ENTRIES=(
    "AA4 0.265"
    "AA3 0.405"
    "AA2 0.62"
    "AA1 1.0"
    "AB5 0.22"
    "AB4 0.337"
    "AB3 0.515"
    "AB2 0.826"
    "AB1 1.214"
    "BA4 0.186"
    "BA3 0.315"
    "BA2 0.552"
    "BA1 1.0"
    "BB5 0.155"
    "BB4 0.265"
    "BB3 0.46"
    "BB2 0.826"
    "BB1 1.37"
    "CA4 0.134"
    "CA3 0.253"
    "CA2 0.493"
    "CA1 1.0"
    "CB4 0.114"
    "CB3 0.21"
    "CB2 0.405"
    "CB1 0.826"
)

# ── Hardcoded SST combos: "STAG_FIX ROT_EFFECT" ──────────────────────────────
# Preset: Sch+Ba / Off+Ba  (2 sims per grid factor)
declare -a SST_COMBOS=(
    "Schwarz Bardina"
    "Off     Bardina"
)

# Short labels for directory/config names
declare -A STAG_SHORT=( [Off]=Off [Schwarz]=Sch )
declare -A ROT_SHORT=(  [Bardina]=Ba )

# ── Helper: patch grid_factor in parameter.yml ────────────────────────────────
patch_grid_factor() {
    local yml="$1"
    local gf="$2"
    sed -i "s/^\(\s*grid_factor:\s*\)[0-9.e+-]*/\1${gf}/" "$yml"
}

# ── Helper: write sim_config.yml ──────────────────────────────────────────────
write_sim_config() {
    local dir="$1"
    local sim_name="$2"
    local gf="$3"
    local stag="$4"
    local rot="$5"
    local jou="$6"

    cat > "${dir}/sim_config.yml" <<EOF
# sim_config.yml — auto-generated by run_study.sh
# ----------------------------------------------------
sim_name:           ${sim_name}
grid_factor:        ${gf}
turbulence_model:   OmegaSST
stagnation_fix:     ${stag}
rotational_effects: ${rot}
journal_file:       ${jou}
EOF
}

# =============================================================================
#  MAIN LOOP
# =============================================================================
total_submitted=0

for entry in "${GF_ENTRIES[@]}"; do
    read -r sim_name gf_val <<< "$entry"

    base_dir="${BASE_DIR}/${sim_name}"

    echo "======================================================================"
    echo "  Grid factor: ${sim_name}  (GF = ${gf_val})"
    echo "======================================================================"

    # ── 1. Patch grid_factor into parameter.yml ────────────────────────────
    echo "  Patching grid_factor = ${gf_val} in ${PARAM_YML}"
    patch_grid_factor "${PARAM_YML}" "${gf_val}"

    # ── 2. Generate base geometry ──────────────────────────────────────────
    echo "  Generating base geometry → ${base_dir}"

    cd /localdata1/testcases/staggered-labyrinth-seal_new/lab_altered_py

    module load pymesh/2.0.1-numpy
    PyMesh.x main.py \
        -p "${PARAM_YML}" \
        -g "${GEO_YML}" \
        -c "${base_dir}"
    module unload pymesh/2.0.1-numpy
    module load trace_suite/9.8.0-double

    cd "${base_dir}/input"

    prep.py -clb -cgns TRACE.cgns -np 128 -sb TRACE_split.cgns splitScript.jou mergeScript.jou
    gmcPlay splitScript.jou

    cp "${PARAM_YML}" "${base_dir}/parameters_used.yml"
    cp "${GEO_YML}"   "${base_dir}/geometry_used.yml"

    # ── Patch TRACE_control.input ──────────────────────────────────────────
    # WriteCellResidual lines intentionally commented out — do not re-enable
    # without checking residual output behaviour first.
    # CONTROL_FILE="${base_dir}/input/TRACE_control.input"
    # printf '\nAll immediate\nWriteCellResidual\n' >> "${CONTROL_FILE}"

    echo "  Base geometry ready: ${base_dir}  (kept in testGEO, not uploaded)"

    # ── 3. Loop over SST combos ────────────────────────────────────────────
    for combo in "${SST_COMBOS[@]}"; do
        read -r stag rot <<< "$combo"

        short_stag="${STAG_SHORT[$stag]}"
        short_rot="${ROT_SHORT[$rot]}"
        jou_file="OmegaSST_${stag}_${rot}.jou"

        variant_name="${sim_name}_${short_stag}_${short_rot}"
        variant_dir="${BASE_DIR}/${variant_name}"
        variant_input="${variant_dir}/input"

        echo "  ----------------------------------------------------------------"
        echo "  Variant : ${variant_name}"
        echo "  Stag fix: ${stag}   Rot effects: ${rot}"
        echo "  Journal : ${jou_file}"
        echo "  ----------------------------------------------------------------"

        # ── a. Copy base dir ───────────────────────────────────────────────
        cp -r "${base_dir}" "${variant_dir}"

        # ── b. Apply SST journal ───────────────────────────────────────────
        cd "${variant_input}"
        gmcPlay "${JOU_DIR}/${jou_file}"

        # ── c. Write sim_config.yml ────────────────────────────────────────
        write_sim_config \
            "${variant_dir}" "${variant_name}" \
            "${gf_val}" "${stag}" "${rot}" "${jou_file}"

        # ── d. Upload variant to HPC (base dir is NOT uploaded) ────────────
        echo "  Uploading ${variant_name} → ${HPC_HOST}:${HPC_SCRATCH}"
        scp -r "${variant_dir}" "${HPC_HOST}:${HPC_SCRATCH}"

        # ── e. Submit sbatch job ───────────────────────────────────────────
        ssh "${HPC_HOST}" \
            "sbatch --chdir=${HPC_SCRATCH}/${variant_name}/input ${SBATCH_SCRIPT}"

        # ── f. Delete variant from testGEO (base stays) ───────────────────
        echo "  Cleaning up variant from testGEO: ${variant_dir}"
        rm -rf "${variant_dir}"

        total_submitted=$(( total_submitted + 1 ))
        echo "  Submitted & cleaned: ${variant_name}"
        echo ""

    done

    echo "  Done with ${sim_name}. Base geometry preserved at: ${base_dir}"
    echo ""

done

echo "======================================================================"
echo "  All done. Total simulations submitted: ${total_submitted}"
echo "======================================================================"
